name: tests
run-name: ${{ github.actor }} is running tests
on: [ push, pull_request, workflow_call ]

jobs:
  setup:
    name: setup
    runs-on: ubuntu-latest
    steps:

      - name: checkout
        uses: actions/checkout@v3

      - name: pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.6.3
      
      - name: node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'pnpm'

      - uses: actions/cache@v3
        with:
          path: node_modules
          key: node_modules
      
      - name: install dependencies
        run: pnpm i

  unit-tests:
    needs: setup
    runs-on: ubuntu-latest
    steps:

      - name: checkout
        uses: actions/checkout@v3

      - name: pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.6.3

      - name: node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'pnpm'

      - uses: actions/cache@v3
        with:
          path: node_modules
          key: node_modules

      - name: test
        run: pnpm run test:unit:ci
      
        if: always()
      - uses: actions/upload-artifact@v3
        with:
          name: unit-test-report
          path: junit.xml
          retention-days: 10

  e2e-tests:
    needs: setup
    runs-on: ubuntu-latest
    steps:

      - name: checkout
        uses: actions/checkout@v3

      - name: pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.6.3
      
      - name: node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'pnpm'

      - uses: actions/cache@v3
        with:
          path: node_modules
          key: node_modules

      - name: install-playwright
        run: npx playwright install --with-deps chromium

      - name: test
        run: pnpm run test:e2e:ci

        if: always()
      - uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 10